[package]
name = "devlog-tracing"
version = "0.1.0"
edition = "2021"
authors = ["hermannm"]

[dependencies]
chrono = "0.4.38"
tracing = "0.1.40"
tracing-core = "0.1.32"
tracing-subscriber = { version = "0.3.18", features = ["chrono"] }
